**The Steepest Descent Algorithm**

In [83]:
import numpy as np
import scipy as sp
from scipy import linalg as lg



# Ax=b

d1=2*np.ones(3)
d2=(-1)*np.ones(2)
A=np.diag(d1)+np.diag(d2,-1)+np.diag(d2,1) # A is a symetric  positive deinete matrix
print('A=',A)
b=np.array([1,1,1])
##########################      python pure     ##################""
xpython=lg.solve(A,b)    # x with python  
print('la solution avec python de Ax=b est :',xpython)
print('Erreur entre inv(A)b et la solution avec python est : ',sp.dot(lg.inv(A),b)-xpython)
print("////////////////////////////////////////////////")
##################         Algorithm   WITH pk=rk     ####################################

x=np.zeros(3)
r=b                        #r(x)=b-Ax
Nmax= 30                    # nombres  des iterations maximal
epsilon=0.000000001

for i in range(1,Nmax+1):
  Ar=sp.dot(A,r)
  alpha=(np.sum(r*r))/(np.sum(Ar*r))
  x=x+alpha*r
  r=r-alpha*Ar
  cond=sp.sum(r*r)
  if sp.sqrt(cond) <= epsilon:
    break
  
print("la méthode converge vers ",x ," dans ",i ," ietration"," avec erreur de ",lg.norm(cond))

A= [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
la solution avec python de Ax=b est : [1.5 2.  1.5]
Erreur entre inv(A)b et la solution avec python est :  [ 0.00000000e+00 -4.44089210e-16 -2.22044605e-16]
////////////////////////////////////////////////
la méthode converge vers  [1.5 2.  1.5]  dans  20  ietration  avec erreur de  3.0000000000009657e-20


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:31: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead


**The Conjugate Gradient Algorithm**

In [84]:
##################         Algorithm   WITH pk=rk+beta*p(k-1)    ####################################

x=np.zeros(3)
r=b                        #r(x)=b-Ax
p=b
Nmax= 30                   # nombres  des iterations maximal
epsilon=0.00000000001

for i in range(1,Nmax+1):
  rk=r
  Ap=sp.dot(A,p)
  alpha=(np.sum(r*r))/(np.sum(Ap*p))
  x=x+alpha*p
  
  r=r-alpha*Ap
  COND=sp.sum(r*r)
  if sp.sqrt(COND) <= epsilon:
    break
  beta=(np.sum(r*r))/(np.sum(rk*rk))
  p=r+beta*p
print("la méthode converge vers ",x ," dans ",i ," ietration"," avec erreur de ",lg.norm(cond))
print('les valeures propres de A sont :',lg.eigvals(A))  # Verification of  the Theorem 2.8.

la méthode converge vers  [1.5 2.  1.5]  dans  2  ietration  avec erreur de  3.0000000000009657e-20
les valeures propres de A sont : [3.41421356+0.j 2.        +0.j 0.58578644+0.j]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead


**The Full Orthogonalisation (FOM) algorithm**

In [180]:
############### Algorithm for linear systems having non symmetric matrix ############
n=A.shape[0]          
x=np.array([0,1,0])
r=b-sp.dot(A,x)                    #r(x)=b-Ax
m=50         # nombres  des iterations maximal 
beta= lg.norm(r)
V=np.zeros((n,m+1))
H=np.zeros((m+1,m))
V[:,0]=(1/beta)*r
epsilon=1e-5
for j in range(m):
  w=sp.dot(A,V[:,j])
  for i in range(j):
    H[i,j]=sp.sum(w*V[:,i])
    w=w-H[i,j]*V[:,i]
  H[j+1,j]=lg.norm(w)
  if H[j+1,j] <= 1e-12  :
    break
  else:
    V[:,j+1]=(1/H[j+1,j])*w

Hm=H[:m,:m]                    # The matrix obtained from H by deletiong its last row  and  we have Hm=trans(Vm)AVM
Vm=V[:m,:m]                        #  V is the orthonormal basis of the Krylov subspace 

e=np.zeros(m)
e[0]=1                        #   e1 

y=sp.dot(lg.inv(Hm),beta*e)                      # In this case Hm is reduces to a tridiagonal matrix because A symmetric
x=x+sp.dot(Vm,y)                   
print("la méthode converge vers ",x)


la méthode converge vers  [1.5 2.  1.5]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:29: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead


**The GMRES algorithm**

In [182]:
#tQ,R=lg.qr(A)                                A=transp(Q)R
#Q=sp.transpose(tQ)
############### Algorithm for linear systems having non symmetric matrix and large problems ############
n=A.shape[0]          
x=np.ones(n)
r=b-sp.dot(A,x)                    #r(x)=b-Ax
m=4              # nombres  des iterations maximal 
beta= lg.norm(r)
V=np.zeros((n,m+1))
H=np.zeros((m+1,m))
V[:,0]=(1/beta)*r

tol=1e-10
while beta>tol:
  for j in range(m):
    w=sp.dot(A,V[:,j])
    for i in range(j):
      H[i,j]=sp.sum(w*V[:,i])
      w=w-H[i,j]*V[:,i]
    H[j+1,j]=lg.norm(w)
    if H[j+1,j] <= 1e-12  :
      break
    else:
      V[:,j+1]=(1/H[j+1,j])*w
  tQ,R=lg.qr(H)
  Q=sp.transpose(tQ)                            #  QR decomposition for H
  e=np.zeros(m+1)
  e[0]=1                        #   e1 
  g=beta*sp.dot(Q,e)
  gm=g[:m]
  Rm=R[:m,:m]                                         # the squars problem solving by using the QR factorization of H
  y=sp.dot(lg.inv(Rm),gm)                             # we can use the LU decopostion to solve Rmy=gm
  Vm=V[:m,:m]                                   
  x=x+sp.dot(Vm,y)

  r=b-sp.dot(A,x)
  beta= lg.norm(r)
  V[:,0]=(1/beta)*r


print("la méthode converge vers ",x)


la méthode converge vers  [1.5 2.  1.5]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:26: DeprecationWarning: scipy.transpose is deprecated and will be removed in SciPy 2.0.0, use numpy.transpose instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:29: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: DeprecationWarning: scipy.dot is deprecated and will be re

**The Symmetric Lanczos Algorithm for Linear Systems**

In [195]:
########################### Algorithm for symtric matrix A############################

n=A.shape[0]          
x=np.ones(n)
r=b-sp.dot(A,x)                    #r(x)=b-Ax
m=3                           # nombres  des iterations maximal 
beta= lg.norm(r)
V=np.zeros((n,m+1))
V[:,0]=(1/beta)*r
alphaT=sp.zeros(m)
betaT=sp.zeros(m+1)
for j in range(m):
  w=sp.dot(A,V[:,j])-betaT[j]*V[:,j-1]
  alphaT[j]=sp.sum(w*V[:,j])
  w=w-alphaT[j]*V[:,j]
  betaT[j+1]=lg.norm(w)
  if betaT[j+1]==0:
    break
  else:
    V[:,j+1]=(1/betaT[j+1])*w
Beta=betaT[1:m]
T=sp.diag(alphaT)+sp.diag(Beta,1)+sp.diag(Beta,-1)
e=np.zeros(m)
e[0]=1

y=beta*sp.dot(lg.inv(T),e)
Vm=V[:m,:m]
x=x+sp.dot(Vm,y)
print("la méthode converge vers ",x)

[1.5 2.  1.5]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.